//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppSqlTableDependency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DummyNotification
    {
        public long NotificationId { get; set; }
        public Nullable<long> UserId { get; set; }
        public int PlayerId { get; set; }
        public short PlatformId { get; set; }
        public Nullable<int> GreaterThan { get; set; }
        public Nullable<int> SmallerThan { get; set; }
        public short NotificationTypeMask { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CurrentPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual PlayerDetail PlayerDetail { get; set; }
    }
}
