//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppSqlTableDependency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerDetail()
        {
            this.DummyNotifications = new HashSet<DummyNotification>();
            this.JournalItems = new HashSet<JournalItem>();
        }
    
        public int PlayerId { get; set; }
        public string PlayerExternalId { get; set; }
        public string PlayerDummywizId { get; set; }
        public string PlayerDummybinId { get; set; }
        public string PlayerDummyheadId { get; set; }
        public int PlayerCardTypeId { get; set; }
        public string PlayerShortName { get; set; }
        public Nullable<int> Pace { get; set; }
        public Nullable<int> Shooting { get; set; }
        public Nullable<int> Passing { get; set; }
        public Nullable<int> Dribbling { get; set; }
        public Nullable<int> Defending { get; set; }
        public Nullable<int> Physical { get; set; }
        public Nullable<int> Age { get; set; }
        public string FacePhotoUrl { get; set; }
        public string BadgePhotoUrl { get; set; }
        public string NationPhotoUrl { get; set; }
        public int Overall { get; set; }
        public string Position { get; set; }
        public string PlayerDBURL { get; set; }
        public string PlayerFullName { get; set; }
        public Nullable<int> CurrentPricePS4 { get; set; }
        public Nullable<int> CurrentPriceXBox { get; set; }
        public Nullable<int> CurrentPricePC { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsTradable { get; set; }
        public Nullable<int> PlayerNationId { get; set; }
        public Nullable<long> PlayerClubId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DummyNotification> DummyNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalItem> JournalItems { get; set; }
    }
}
